export const ADD_FILM='ADD_FILM'
export const REMOVE_FILM='REMOVE_FILM'
export const EDIT_FILM='EDIT_FILM'
export const SEARCH_NAME='SEARCH_NAME'
export const SEARCH_RATING='SEARCH_RATING'
export const AXIOS_CARDS='Axios_Cards'